name: Upload APK

on:
  push:
    branches:
      - main  # or the branch you want to trigger the upload workflow on

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Upload APK
      run: |
        # Use your script or command to upload the APK
        # Example using curl:
        curl -X POST -F "apk=@app/build/outputs/apk/debug/app-debug.apk" \
          https://knightcoder.in/test/upload.php
